# Generated by Django 5.2.4 on 2026-04-02 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(help_text='Поставьте галочку, если снаряжение выдано.', verbose_name='Выдано')),
                ('date_take', models.DateTimeField(null=True, verbose_name='Дата выдачи')),
                ('description', models.CharField(null=True, verbose_name='Описание')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Зарезервированная/выданная единица снаряжения',
                'verbose_name_plural': 'Зарезервированное/выданное снаряжение',
                'ordering': ['equipment'],
            },
        ),
        migrations.CreateModel(
            name='ReservingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Карта резервирования',
                'verbose_name_plural': 'Карты резервирования',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.CharField(null=True, verbose_name='Описание')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Единица снаряжения',
                'verbose_name_plural': 'Снаряжение',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoryEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_take', models.DateTimeField(verbose_name='Дата выдачи')),
                ('date_return', models.DateTimeField(verbose_name='Дата сдачи')),
                ('description', models.CharField(null=True, verbose_name='Описание')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_equipment', to='api.equipment', verbose_name='Единица снаряжения')),
            ],
            options={
                'verbose_name': 'История использования снаряжения',
                'verbose_name_plural': 'История использования снаряжения',
                'ordering': ['equipment'],
            },
        ),
    ]
