# Generated by Django 5.2.4 on 2025-10-25 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('description', models.CharField(null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Единица снаряжения',
                'verbose_name_plural': 'Единичное снаряжение',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoryEquipmentMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_take', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('date_return', models.DateTimeField(verbose_name='Дата сдачи')),
                ('amount', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Единица снаряжения',
                'verbose_name_plural': 'Количественное снаряжение',
                'ordering': ['equipment_many'],
            },
        ),
        migrations.CreateModel(
            name='HistoryRope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_take', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('date_return', models.DateTimeField(verbose_name='Дата сдачи')),
            ],
            options={
                'verbose_name': 'Верёвка',
                'verbose_name_plural': 'Верёвки',
                'ordering': ['rope'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(help_text='Поставьте галочку, если снаряжение выдано.', verbose_name='Статус')),
                ('date_take', models.DateTimeField(verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Единица снаряжения',
                'verbose_name_plural': 'Единичное снаряжение',
                'ordering': ['equipment'],
            },
        ),
        migrations.CreateModel(
            name='ReservationMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(help_text='Поставьте галочку, если снаряжение выдано.', verbose_name='Статус')),
                ('date_take', models.DateTimeField(verbose_name='Дата выдачи')),
                ('amount', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Единица снаряжения',
                'verbose_name_plural': 'Количественное снаряжение',
                'ordering': ['equipment_many'],
            },
        ),
        migrations.CreateModel(
            name='ReservationRope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(help_text='Поставьте галочку, если снаряжение выдано.', verbose_name='Статус')),
                ('date_take', models.DateTimeField(verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Верёвка',
                'verbose_name_plural': 'Верёвки',
                'ordering': ['rope'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMany',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.equipment')),
                ('amount', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Единица снаряжения',
                'verbose_name_plural': 'Количественное снаряжение',
                'ordering': ['name'],
            },
            bases=('api.equipment',),
        ),
        migrations.CreateModel(
            name='Rope',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.equipment')),
                ('length', models.IntegerField(verbose_name='Длина')),
            ],
            options={
                'verbose_name': 'Верёвка',
                'verbose_name_plural': 'Верёвки',
                'ordering': ['name'],
            },
            bases=('api.equipment',),
        ),
        migrations.CreateModel(
            name='HistoryEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_take', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('date_return', models.DateTimeField(verbose_name='Дата сдачи')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipment', verbose_name='Единица снаряжения')),
            ],
            options={
                'verbose_name': 'Единица снаряжения',
                'verbose_name_plural': 'Единичное снаряжение',
                'ordering': ['equipment'],
            },
        ),
    ]
