# Generated by Django 5.2.4 on 2025-11-20 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_equipment', to='api.equipment', verbose_name='Единица снаряжения'),
        ),
    ]
