# Generated by Django 5.2.4 on 2025-10-25 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historyequipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='historyequipmentmany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='historyrope',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipment', verbose_name='Единица снаряжения'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='reservationmany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='reservationrope',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='reservationmany',
            name='equipment_many',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipmentmany', verbose_name='Снаряжение'),
        ),
        migrations.AddField(
            model_name='historyequipmentmany',
            name='equipment_many',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipmentmany', verbose_name='Единица снаряжения'),
        ),
        migrations.AddField(
            model_name='reservationrope',
            name='rope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rope', verbose_name='Верёвка'),
        ),
        migrations.AddField(
            model_name='historyrope',
            name='rope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rope', verbose_name='Единица снаряжения'),
        ),
    ]
