# Generated by Django 5.2.4 on 2025-11-20 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_historyequipment_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_take',
            field=models.DateTimeField(null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='reservingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservingcart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
