# Generated by Django 5.2.4 on 2025-10-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['equipment'], 'verbose_name': 'Зарезервированная/выданная единица снаряжения', 'verbose_name_plural': 'Зарезервированное/выданное единичное снаряжение'},
        ),
        migrations.AlterModelOptions(
            name='reservationmany',
            options={'ordering': ['equipment_many'], 'verbose_name': 'Зарезервированная/выданная единица снаряжения', 'verbose_name_plural': 'Зарезервированное/выданное количественное снаряжение'},
        ),
        migrations.AlterModelOptions(
            name='reservationrope',
            options={'ordering': ['rope'], 'verbose_name': 'Зарезервированная/выданная верёвка', 'verbose_name_plural': 'Зарезервированная/выданная верёвка'},
        ),
    ]
