# Generated by Django 5.2.4 on 2025-11-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_equipment_name_alter_reservation_date_take_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyequipment',
            name='date_return',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи'),
        ),
    ]
