# Generated by Django 5.2.4 on 2025-10-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmany',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.BooleanField(help_text='Поставьте галочку, если снаряжение выдано.', verbose_name='Выдано'),
        ),
        migrations.AlterField(
            model_name='reservationmany',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='reservationmany',
            name='status',
            field=models.BooleanField(help_text='Поставьте галочку, если снаряжение выдано.', verbose_name='Выдано'),
        ),
        migrations.AlterField(
            model_name='reservationrope',
            name='status',
            field=models.BooleanField(help_text='Поставьте галочку, если снаряжение выдано.', verbose_name='Выдано'),
        ),
    ]
