# Generated by Django 5.2.4 on 2025-11-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_historyequipment_date_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_equipment', to='api.equipment', verbose_name='Единица снаряжения'),
        ),
    ]
