# Generated by Django 5.2.4 on 2025-11-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_reservation_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyequipment',
            name='date_return',
            field=models.DateTimeField(verbose_name='Дата сдачи'),
        ),
    ]
