# Generated by Django 5.2.4 on 2025-11-28 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_historyequipment_date_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservingcart',
            options={'ordering': ['user'], 'verbose_name': 'Карта резервирования', 'verbose_name_plural': 'Связи ингредиентов и рецептов'},
        ),
        migrations.AddConstraint(
            model_name='reservingcart',
            constraint=models.UniqueConstraint(fields=('user', 'equipment'), name='duplicate_user_equipments', violation_error_message='Нельзя добавить один вид снаряжения дважды'),
        ),
    ]
