# Generated by Django 5.2.4 on 2025-11-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_reservingcart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservingcart',
            options={'ordering': ['user'], 'verbose_name': 'Карта резервирования', 'verbose_name_plural': 'Карты резервирования'},
        ),
    ]
